INSERT INTO district(name_district) VALUES('Амвросиевский');
INSERT INTO district(name_district) VALUES('Александровский');
INSERT INTO district(name_district) VALUES('Бахмутский');
INSERT INTO district(name_district) VALUES('Великоновоселковский');
INSERT INTO district(name_district) VALUES('Волновахский');
INSERT INTO district(name_district) VALUES('Добропольский');
INSERT INTO district(name_district) VALUES('Константиновский');
INSERT INTO district(name_district) VALUES('Мангушский');
INSERT INTO district(name_district) VALUES('Новоазовский')